//go:build !ignore_autogenerated

/*
 * Copyright 2025 The ChaosBlade Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ChaosBlade) DeepCopyInto(out *ChaosBlade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ChaosBlade) DeepCopy() *ChaosBlade {
	if in == nil {
		return nil
	}
	out := new(ChaosBlade)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosBlade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosBladeList) DeepCopyInto(out *ChaosBladeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosBlade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChaosBladeList) DeepCopy() *ChaosBladeList {
	if in == nil {
		return nil
	}
	out := new(ChaosBladeList)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosBladeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosBladeSpec) DeepCopyInto(out *ChaosBladeSpec) {
	*out = *in
	if in.Experiments != nil {
		in, out := &in.Experiments, &out.Experiments
		*out = make([]ExperimentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChaosBladeSpec) DeepCopy() *ChaosBladeSpec {
	if in == nil {
		return nil
	}
	out := new(ChaosBladeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosBladeStatus) DeepCopyInto(out *ChaosBladeStatus) {
	*out = *in
	if in.ExpStatuses != nil {
		in, out := &in.ExpStatuses, &out.ExpStatuses
		*out = make([]ExperimentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChaosBladeStatus) DeepCopy() *ChaosBladeStatus {
	if in == nil {
		return nil
	}
	out := new(ChaosBladeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ExperimentSpec) DeepCopyInto(out *ExperimentSpec) {
	*out = *in
	if in.Matchers != nil {
		in, out := &in.Matchers, &out.Matchers
		*out = make([]FlagSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ExperimentSpec) DeepCopy() *ExperimentSpec {
	if in == nil {
		return nil
	}
	out := new(ExperimentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ExperimentStatus) DeepCopyInto(out *ExperimentStatus) {
	*out = *in
	if in.ResStatuses != nil {
		in, out := &in.ResStatuses, &out.ResStatuses
		*out = make([]ResourceStatus, len(*in))
		copy(*out, *in)
	}
}

func (in *ExperimentStatus) DeepCopy() *ExperimentStatus {
	if in == nil {
		return nil
	}
	out := new(ExperimentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *FlagSpec) DeepCopyInto(out *FlagSpec) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *FlagSpec) DeepCopy() *FlagSpec {
	if in == nil {
		return nil
	}
	out := new(FlagSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
}

func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}
