// Code generated by scripts/version.sh. DO NOT EDIT.

package version

import "time"

var (
	// Ver 版本号
	Ver = "1.8.0"

	// GitTag Git标签
	GitTag = "v1.8.0"

	// GitCommit Git提交哈希
	GitCommit = "dcebc57"

	// GitBranch Git分支
	GitBranch = "master"

	// BuildTime 构建时间
	BuildTime = "2026-01-09 09:35:50 UTC"

	// BuildTimeParsed 解析后的构建时间
	BuildTimeParsed, _ = time.Parse("2006-01-02 15:04:05 UTC", BuildTime)
)

// GetVersionInfo 获取完整的版本信息
func GetVersionInfo() map[string]string {
	return map[string]string{
		"version":   Ver,
		"gitTag":    GitTag,
		"gitCommit": GitCommit,
		"gitBranch": GitBranch,
		"buildTime": BuildTime,
	}
}

// IsRelease 是否为发布版本
func IsRelease() bool {
	return GitTag != "" && GitTag != "dev"
}

// IsDev 是否为开发版本
func IsDev() bool {
	return !IsRelease()
}
