"""Planning handoff strip — the phase-handoff-context-stripping pinning suite.

Covers the spec's core scenarios with pure-function tests over
``select_strip_targets`` / ``planning_handoff`` plus REAL ``add_messages``
reducer runs for the deletion semantics (RemoveMessage by id), the replan
full-loop (two rounds, each strip bounded by its own attribution epoch),
the compaction interaction (both orderings), the kickoff-scan
compatibility, and the replica-fallback survival in the retained zone.

The anchor whitelist contract under test:
- anchors (FAULT INTENT, probe hints) are marked at GENERATION time and
  survive the strip;
- everything else inside [attribution_epoch_index, finalized) is removed
  — AI turns, tool results, in-loop corrective feedback;
- messages before the epoch boundary (prior rounds' finalized markers,
  kickoffs, execution receipts, verification evidence) are the replan's
  input and are never removed;
- the finalized marker and everything after it are retained;
- persist-then-remove ordering with skip-on-failure (archive first).
"""

from langchain_core.messages import (
    AIMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langgraph.graph.message import add_messages
from unittest.mock import AsyncMock, MagicMock

import pytest

from chaos_agent.agent.nodes.planning.handoff_strip import (
    CONTEXT_ANCHOR_FLAG,
    planning_handoff,
    select_strip_targets,
    _epoch_start,
    _find_finalized_idx,
)

TASK_ID = "task-strip-test"


# ---------------------------------------------------------------------------
# Fixtures: realistic message sequences (ids auto-generated by langchain).
# ---------------------------------------------------------------------------


def _anchor_fault_intent() -> HumanMessage:
    return HumanMessage(
        content=(
            "[FAULT INTENT — UNVERIFIED parameters from user dialogue]\n"
            "Fault type: memory\nScope: node\nTarget: worker-1"
        ),
        additional_kwargs={CONTEXT_ANCHOR_FLAG: True},
    )


def _anchor_probe_hints() -> SystemMessage:
    return SystemMessage(
        content=(
            "[Pre-task environment probes — collected at task start, hints only]\n"
            "- chaosblade_operator [ok]: running"
        ),
        additional_kwargs={CONTEXT_ANCHOR_FLAG: True},
    )


def _ai_probe_turn(call_id: str, v_args: str) -> AIMessage:
    return AIMessage(
        content="",
        tool_calls=[{
            "name": "kubectl",
            "args": {"subcommand": "get", "v_args": v_args},
            "id": call_id,
            "type": "tool_call",
        }],
    )


def _tool_result(call_id: str, content: str) -> ToolMessage:
    return ToolMessage(content=content, tool_call_id=call_id, name="kubectl")


def _runtime_evidence_hint() -> HumanMessage:
    # persist_corrective_hint family: in-loop human feedback — stripped.
    return HumanMessage(
        content="[RUNTIME EVIDENCE] The operator pod is NOT ready — revise."
    )


def _finalized(summary: str = "inject node-mem via blade") -> ToolMessage:
    return ToolMessage(
        content=f"Planning finalized. Summary: {summary}",
        tool_call_id="call-finish",
        name="finish_planning",
    )


def _finish_planning_caller(
    call_id: str = "call-finish",
    extra_calls: list | None = None,
) -> AIMessage:
    """The AIMessage that issued finish_planning (optionally parallel calls)."""
    calls = [{
        "name": "finish_planning",
        "args": {"summary": "inject"},
        "id": call_id,
        "type": "tool_call",
    }]
    calls.extend(extra_calls or [])
    return AIMessage(content="", tool_calls=calls)


def _kickoff() -> HumanMessage:
    return HumanMessage(content="**PHASE 2 — EXECUTE NOW** proceed with step 1.")


def _exec_receipt() -> ToolMessage:
    return ToolMessage(
        content='{"success": true, "uid": "exp-123", "code": 200}',
        tool_call_id="call-exec",
        name="blade_create",
    )


def _verify_turn() -> AIMessage:
    return AIMessage(content="Sampling memory usage to confirm the fault...")


def _first_pass_sequence() -> list:
    """A realistic first-pass planning round + downstream execution/verify.

    Runs through the REAL ``add_messages`` reducer first: production
    messages always enter state via the reducer, which assigns ids to
    every id-less message (RemoveMessage needs them) — the fixture must
    mirror that path, not raw constructors.
    """
    seq = [
        _anchor_fault_intent(),
        _anchor_probe_hints(),
        _ai_probe_turn("c1", "nodes"),
        _tool_result("c1", "NAME STATUS ROLES\nworker-1 Ready <none>"),
        _ai_probe_turn("c2", "get pods -n chaosblade"),
        _tool_result("c2", 'NAME READY STATUS\nblade-op-1 1/1 Running'),
        _runtime_evidence_hint(),
        _finalized(),
        _kickoff(),
        _exec_receipt(),
        _verify_turn(),
    ]
    return list(add_messages([], seq))


# ---------------------------------------------------------------------------
# Fake session store — records appends, optionally fails.
# ---------------------------------------------------------------------------


class _FakeStore:
    """Happy-path store: appends land and read back like a healthy disk."""

    def __init__(self, preexisting=None):
        self.appends: list[tuple[str, list, str]] = []
        self._preexisting = list(preexisting or [])

    def append_messages(self, task_id, messages, node_name=""):
        self.appends.append((task_id, list(messages), node_name))

    def read_session(self, task_id):
        from chaos_agent.memory.session_store import _serialize_message_full

        archived = list(self._preexisting)
        for _, msgs, _node in self.appends:
            archived.extend(msgs)
        return {"messages": [_serialize_message_full(m) for m in archived]}


class _FailingStore:
    def append_messages(self, task_id, messages, node_name=""):
        raise OSError("disk full")


class _SilentSwallowStore:
    """Mirrors the REAL fire-and-forget contract: append_messages returns
    normally even when nothing landed (missing active session, swallowed
    disk-write failure). Exception-based guards see success here; only
    the read-back verification can tell the difference."""

    def __init__(self, read_result=None):
        self.appends: list[tuple[str, list, str]] = []
        self._read_result = read_result  # None → task unknown

    def append_messages(self, task_id, messages, node_name=""):
        self.appends.append((task_id, list(messages), node_name))

    def read_session(self, task_id):
        return self._read_result


def _patch_store(monkeypatch, store):
    import chaos_agent.memory.session_store as ss

    monkeypatch.setattr(ss, "get_global_session_store", lambda: store)


# ---------------------------------------------------------------------------
# Selection rule (pure function).
# ---------------------------------------------------------------------------


class TestSelectStripTargets:
    """Anchor whitelist inside the epoch-bounded range."""

    def test_anchors_retained_process_messages_stripped(self):
        seq = _first_pass_sequence()
        finalized_idx = _find_finalized_idx(seq)
        targets = select_strip_targets(seq, 0, finalized_idx)

        target_ids = {t.id for t in targets}
        # Anchors survive.
        assert seq[0].id not in target_ids  # FAULT INTENT
        assert seq[1].id not in target_ids  # probe hints
        # Finalized and everything after survive.
        for m in seq[finalized_idx:]:
            assert m.id not in target_ids
        # The planning round's process messages are stripped: AI turns,
        # tool results, in-loop corrective feedback.
        for m in seq[2:finalized_idx]:
            assert m.id in target_ids
        assert len(targets) == finalized_idx - 2

    def test_finalization_caller_exempt_from_strip(self):
        """B44: the finish_planning caller must survive the strip.

        Stripping the caller orphaned the retained ``Planning finalized``
        ToolMessage — sanitize_tool_pairing then dropped that orphan
        before EVERY downstream LLM call (case-32: six drops across the
        inject and recover graphs), so the summary the strip meant to
        hand to execution never reached a model.
        """
        seq = list(add_messages([], [
            _anchor_fault_intent(),               # 0
            _ai_probe_turn("c1", "nodes"),        # 1
            _tool_result("c1", "NAME STATUS"),    # 2
            _finish_planning_caller(),            # 3 — caller of finalized
            _finalized(),                         # 4
            _kickoff(),                           # 5
        ]))
        finalized_idx = _find_finalized_idx(seq)
        assert finalized_idx == 4

        targets = select_strip_targets(seq, 0, finalized_idx)
        target_ids = {t.id for t in targets}

        # Probe turn still stripped.
        assert seq[1].id in target_ids
        assert seq[2].id in target_ids
        # The caller is exempt: finalized keeps its AIMessage pair.
        assert seq[3].id not in target_ids

    def test_parallel_finalization_batch_tool_results_exempt(self):
        """A parallel finish_planning + probe turn keeps its whole batch paired.

        Exempting only the caller AIMessage would trade one orphan for
        another when the finalization turn carried sibling tool_calls
        whose ToolMessages land inside the strip range.
        """
        seq = list(add_messages([], [
            _anchor_fault_intent(),               # 0
            _finish_planning_caller("call-finish", extra_calls=[{
                "name": "kubectl",
                "args": {"subcommand": "get", "v_args": "nodes"},
                "id": "c9",
                "type": "tool_call",
            }]),                                 # 1 — batch of 2 calls
            _tool_result("c9", "NAME STATUS"),    # 2 — sibling result in range
            _finalized(),                         # 3
        ]))
        finalized_idx = _find_finalized_idx(seq)
        assert finalized_idx == 3

        targets = select_strip_targets(seq, 0, finalized_idx)
        target_ids = {t.id for t in targets}

        # Whole finalization batch survives: caller + sibling result.
        assert seq[1].id not in target_ids
        assert seq[2].id not in target_ids
        assert targets == []

    def test_epoch_boundary_excludes_prior_round_evidence(self):
        # Replan scenario: round-1 execution/verification evidence sits
        # BEFORE the epoch boundary and must survive the round-2 strip.
        seq = list(add_messages([], [
            _anchor_fault_intent(),       # 0
            _anchor_probe_hints(),        # 1
            _ai_probe_turn("c1", "nodes"),  # 2  (round 1 planning)
            _tool_result("c1", "..."),    # 3
            _finalized("round 1 plan"),   # 4
            _kickoff(),                   # 5
            _exec_receipt(),              # 6
            _verify_turn(),               # 7
            # ── replan seam: epoch reset here → epoch = 8 ──
            _ai_probe_turn("c3", "describe node worker-1"),  # 8 (round 2)
            _tool_result("c3", "..."),    # 9
            _runtime_evidence_hint(),     # 10
            _finalized("round 2 plan"),   # 11
            _kickoff(),                   # 12
            _exec_receipt(),              # 13
        ]))
        epoch = 8
        finalized_idx = _find_finalized_idx(seq)
        assert finalized_idx == 11

        targets = select_strip_targets(seq, epoch, finalized_idx)
        target_ids = {t.id for t in targets}

        # Round-2 planning messages (8..10) stripped.
        for m in seq[epoch:finalized_idx]:
            assert m.id in target_ids
        # Round-1 evidence BEFORE the boundary survives: old finalized,
        # kickoff, execution receipt, verification turn, plus anchors.
        for m in seq[:epoch]:
            assert m.id not in target_ids
        # New finalized and after survive.
        for m in seq[finalized_idx:]:
            assert m.id not in target_ids

    def test_epoch_at_or_after_finalized_selects_nothing(self):
        # Batch iteration with a stale durable epoch: boundary lands at or
        # after the new marker → empty range, fail-safe toward keeping.
        seq = [_finalized(), _kickoff()]
        assert select_strip_targets(seq, 5, 0) == []
        assert select_strip_targets(seq, 2, 0) == []

    def test_idless_messages_never_selected(self):
        ai = AIMessage(content="thinking")  # no id
        finalized = _finalized()
        seq = [ai, finalized]
        targets = select_strip_targets(seq, 0, 1)
        assert targets == []

    def test_negative_or_none_finalized_selects_nothing(self):
        assert select_strip_targets([_finalized()], 0, None) == []


class TestEpochStart:
    def test_missing_key_is_zero(self):
        assert _epoch_start({}) == 0

    def test_garbage_value_is_zero(self):
        assert _epoch_start({"attribution_epoch_index": "garbage"}) == 0
        assert _epoch_start({"attribution_epoch_index": None}) == 0

    def test_negative_clamped_to_zero(self):
        assert _epoch_start({"attribution_epoch_index": -3}) == 0

    def test_valid_value_passes_through(self):
        assert _epoch_start({"attribution_epoch_index": 8}) == 8


# ---------------------------------------------------------------------------
# Node entry: idempotency, persist-then-remove, epoch invariance.
# ---------------------------------------------------------------------------


class TestPlanningHandoffNode:
    def _state(self, seq, epoch=None):
        state = {"messages": list(seq), "task_id": TASK_ID}
        if epoch is not None:
            state["attribution_epoch_index"] = epoch
        return state

    def test_no_finalized_marker_no_state_change(self, monkeypatch):
        _patch_store(monkeypatch, _FakeStore())
        seq = [_anchor_fault_intent(), _anchor_probe_hints(), _ai_probe_turn("c1", "nodes")]
        assert planning_handoff(self._state(seq)) == {}

    def test_returns_only_messages_key_epoch_untouched(self, monkeypatch):
        # The invariant's first half: the node's state update never carries
        # attribution_epoch_index — the reducer leaves it numerically
        # unchanged because the strip only removes AFTER the boundary.
        _patch_store(monkeypatch, _FakeStore())
        seq = _first_pass_sequence()
        result = planning_handoff(self._state(seq, epoch=0))
        assert set(result.keys()) == {"messages"}
        assert "attribution_epoch_index" not in result

    def test_persist_then_remove_ordering(self, monkeypatch):
        # Archive BEFORE removal: the store receives the ORIGINAL messages
        # (not RemoveMessage wrappers), and the returned removals match
        # exactly those ids.
        store = _FakeStore()
        _patch_store(monkeypatch, store)
        seq = _first_pass_sequence()
        result = planning_handoff(self._state(seq))

        assert len(store.appends) == 1
        task_id, archived, node_name = store.appends[0]
        assert task_id == TASK_ID
        assert node_name == "planning_handoff"
        removal_ids = {r.id for r in result["messages"]}
        assert removal_ids == {m.id for m in archived}
        # No RemoveMessage reaches the archive path.
        from langchain_core.messages import RemoveMessage
        assert not any(isinstance(m, RemoveMessage) for m in archived)
        # Anchors are neither archived (they are not stripped) nor removed.
        assert seq[0].id not in removal_ids
        assert seq[1].id not in removal_ids

    def test_idempotent_reentry_after_reducer_application(self, monkeypatch):
        # Positional idempotency: apply the removals via the REAL reducer,
        # re-run the node → nothing left to do.
        _patch_store(monkeypatch, _FakeStore())
        seq = _first_pass_sequence()
        state = self._state(seq, epoch=0)

        first = planning_handoff(state)
        assert first, "first pass must strip"

        state["messages"] = add_messages(state["messages"], first["messages"])
        second = planning_handoff(state)
        assert second == {}

    def test_persistence_failure_skips_strip(self, monkeypatch):
        _patch_store(monkeypatch, _FailingStore())
        seq = _first_pass_sequence()
        assert planning_handoff(self._state(seq)) == {}

    def test_silent_missing_session_skips_strip(self, monkeypatch):
        # append_messages returns NORMALLY when the task has no active
        # session ("Task not found, skipping append") — no exception is
        # ever raised. Only the read-back catches it.
        store = _SilentSwallowStore(read_result=None)
        _patch_store(monkeypatch, store)
        seq = _first_pass_sequence()
        assert planning_handoff(self._state(seq)) == {}
        assert store.appends, "append was attempted (and silently dropped)"

    def test_silent_disk_write_failure_skips_strip(self, monkeypatch):
        # Round-5 audit: append_messages swallows disk-write failures on
        # purpose (fire-and-forget archival contract). The read-back
        # reads from disk, so the swallowed write reads back as missing.
        from chaos_agent.memory.session_store import _serialize_message_full

        seq = _first_pass_sequence()
        # Disk snapshot exists but holds only the anchors — the strip's
        # write never landed.
        disk = {"messages": [_serialize_message_full(seq[0]),
                              _serialize_message_full(seq[1])]}
        store = _SilentSwallowStore(read_result=disk)
        _patch_store(monkeypatch, store)
        assert planning_handoff(self._state(seq)) == {}
        assert store.appends, "append was attempted (and silently dropped)"

    def test_readback_covers_preexisting_archive(self, monkeypatch):
        # Dedup semantics: messages the pre_reason_hook flush already
        # archived are skipped by append_messages but MUST read back as
        # present — the strip proceeds for the full target set (the
        # pre-existing entries simply dedup out of the append).
        seq = _first_pass_sequence()
        store = _FakeStore(preexisting=[seq[2], seq[3]])  # flushed earlier
        _patch_store(monkeypatch, store)
        result = planning_handoff(self._state(seq))
        assert result and len(result["messages"]) == 5
        appended_ids = {m.id for _, msgs, _ in store.appends for m in msgs}
        assert appended_ids == {seq[i].id for i in (2, 3, 4, 5, 6)}

    def test_no_task_id_skips_strip(self, monkeypatch):
        _patch_store(monkeypatch, _FakeStore())
        seq = _first_pass_sequence()
        assert planning_handoff({"messages": list(seq)}) == {}

    def test_no_store_skips_strip(self, monkeypatch):
        _patch_store(monkeypatch, None)
        seq = _first_pass_sequence()
        assert planning_handoff(self._state(seq)) == {}


# ---------------------------------------------------------------------------
# Reducer semantics + replan full loop (two rounds) + epoch invariance.
# ---------------------------------------------------------------------------


class TestReducerSemantics:
    def test_removals_delete_by_id_via_real_reducer(self, monkeypatch):
        _patch_store(monkeypatch, _FakeStore())
        seq = _first_pass_sequence()
        state = {"messages": list(seq), "task_id": TASK_ID}

        result = planning_handoff(state)
        stripped = add_messages(state["messages"], result["messages"])

        surviving_ids = [m.id for m in stripped]
        assert seq[2].id not in surviving_ids  # AI probe turn
        assert seq[3].id not in surviving_ids  # tool result
        assert seq[6].id not in surviving_ids  # RUNTIME EVIDENCE hint
        # Order and content of survivors preserved (anchors + finalized +
        # downstream).
        assert [m.id for m in stripped] == [
            seq[0].id, seq[1].id, seq[7].id, seq[8].id, seq[9].id, seq[10].id,
        ]

    def test_two_replan_rounds_strip_only_own_round(self, monkeypatch):
        """3.4 replan full loop: each handoff strips its own planning round;
        prior rounds' execution/verification evidence survives as the
        replan's input; attribution never resurrects pre-seam attempts.
        The three seam sites (execute_loop / plan_change_confirm /
        _verifier_finalize) are graph-wired back into agent_loop (pinned
        in test_graph_invariants), so this semantics test plus that
        topology pinning covers all three replan paths."""
        store = _FakeStore()
        _patch_store(monkeypatch, store)

        round1 = _first_pass_sequence()  # 11 messages, finalized at idx 7
        state = {"messages": list(round1), "task_id": TASK_ID}

        # Handoff 1: strips round-1 planning (idx 2..6).
        h1 = planning_handoff(state)
        state["messages"] = add_messages(state["messages"], h1["messages"])
        epoch1 = len(state["messages"])  # seam lands at the current length

        # Verify failure → replan seam resets the attribution epoch.
        state["attribution_epoch_index"] = epoch1

        # Round 2 planning (replan): fresh probe turns + feedback.
        round2 = list(add_messages([], [
            _ai_probe_turn("c3", "describe node worker-1"),
            _tool_result("c3", "Allocatable: 16Gi"),
            _runtime_evidence_hint(),
            _finalized("round 2 plan — fallback to native"),
            _kickoff(),
            _exec_receipt(),
            _verify_turn(),
        ]))
        state["messages"] = add_messages(state["messages"], round2)

        # Handoff 2: strips ONLY round-2 planning (the new epoch range).
        h2 = planning_handoff(state)
        assert h2, "round-2 strip must fire"
        removal2_ids = {r.id for r in h2["messages"]}
        assert removal2_ids == {round2[0].id, round2[1].id, round2[2].id}

        state["messages"] = add_messages(state["messages"], h2["messages"])

        surviving = [m.id for m in state["messages"]]
        # Round-1 anchors, finalized, kickoff, receipt, verify survive.
        for i in (0, 1, 7, 8, 9, 10):
            assert round1[i].id in surviving
        # Round-1 planning turns are gone.
        for i in (2, 3, 4, 5, 6):
            assert round1[i].id not in surviving
        # Round-2 finalized/kickoff/receipt/verify survive.
        for m in round2[3:]:
            assert m.id in surviving

        # 2.4 archive pinning: BOTH stripped planning rounds are in the
        # task JSON — two persist batches, together carrying every removed
        # message (dedup-key idempotence in the real store absorbs the
        # hook-flush double writes).
        assert len(store.appends) == 2
        archived_ids = {m.id for _, batch, _ in store.appends for m in batch}
        assert archived_ids == {
            round1[i].id for i in (2, 3, 4, 5, 6)
        } | {round2[i].id for i in (0, 1, 2)}

    def test_epoch_index_invariance_across_strip(self, monkeypatch):
        """3.2 invariance: epoch value unchanged; the epoch-bounded slice
        consumed by attribution scans keeps its execution evidence intact
        (the strip only removes planning turns inside the range)."""
        _patch_store(monkeypatch, _FakeStore())
        seq = _first_pass_sequence()
        epoch = 0
        state = {
            "messages": list(seq),
            "task_id": TASK_ID,
            "attribution_epoch_index": epoch,
        }

        result = planning_handoff(state)
        assert "attribution_epoch_index" not in result
        state["messages"] = add_messages(state["messages"], result["messages"])

        assert state["attribution_epoch_index"] == epoch
        # The epoch slice still carries the execution receipt + verify turn
        # (attribution scans read ToolMessages like blade_create receipts).
        slice_msgs = state["messages"][state["attribution_epoch_index"]:]
        slice_ids = {m.id for m in slice_msgs}
        assert seq[9].id in slice_ids  # blade_create receipt
        assert seq[10].id in slice_ids  # verification turn


# ---------------------------------------------------------------------------
# Kickoff-scan compatibility (3.5).
# ---------------------------------------------------------------------------


class TestKickoffScanCompat:
    def test_kickoff_scan_semantics_unchanged_across_strip(self, monkeypatch):
        # _phase2_kickoff_needed reverse-scans for the LAST finalized
        # marker — the strip leaves it (and everything after) intact, so
        # the positional scan returns the SAME verdict before and after
        # the strip, both when armed (no kickoff after finalized) and
        # when already announced (kickoff present).
        from chaos_agent.agent.nodes.execute.execute_loop import (
            _phase2_kickoff_needed,
        )

        _patch_store(monkeypatch, _FakeStore())

        # Armed case: finalized but no kickoff/productive AI after it.
        seq = list(add_messages([], [
            _anchor_fault_intent(),
            _anchor_probe_hints(),
            _ai_probe_turn("c1", "nodes"),
            _tool_result("c1", "..."),
            _finalized(),
            _verify_turn(),
        ]))
        state = {"messages": list(seq), "task_id": TASK_ID}
        assert _phase2_kickoff_needed(state["messages"]) is True

        result = planning_handoff(state)
        state["messages"] = add_messages(state["messages"], result["messages"])
        # Finalized marker still located, still the newest signal → armed.
        assert _phase2_kickoff_needed(state["messages"]) is True

        # Once the kickoff lands (execute_loop emits it), the scan disarms —
        # the message stays in the retained zone.
        state["messages"] = add_messages(state["messages"], [_kickoff()])
        assert _phase2_kickoff_needed(state["messages"]) is False

    def test_kickoff_marker_survives_strip(self, monkeypatch):
        # The full first-pass sequence already carries a kickoff in the
        # retained zone: after the strip it is still there, still disarming
        # the scan (kickoff semantics unchanged).
        from chaos_agent.agent.nodes.execute.execute_loop import (
            _phase2_kickoff_needed,
        )

        _patch_store(monkeypatch, _FakeStore())
        seq = _first_pass_sequence()
        state = {"messages": list(seq), "task_id": TASK_ID}
        assert _phase2_kickoff_needed(state["messages"]) is False

        result = planning_handoff(state)
        state["messages"] = add_messages(state["messages"], result["messages"])
        assert _phase2_kickoff_needed(state["messages"]) is False
        surviving_ids = [m.id for m in state["messages"]]
        assert seq[8].id in surviving_ids  # the kickoff itself


# ---------------------------------------------------------------------------
# Compaction interaction (3.3): both orderings compose.
# ---------------------------------------------------------------------------


class TestCompactionInteraction:
    def test_handoff_then_compaction(self, monkeypatch):
        # Handoff removes AFTER the epoch boundary and leaves the index;
        # compaction then removes BEFORE the boundary and re-bases. The
        # two mechanisms never delete from the same side — the re-base
        # counts survivors before the boundary, and the handoff deleted
        # none of those, so the arithmetic stays correct.
        from chaos_agent.memory.hook import _rebase_epoch_index

        _patch_store(monkeypatch, _FakeStore())

        # Two-round state: round-1 already handoff-stripped.
        seq = _first_pass_sequence()
        state = {"messages": list(seq), "task_id": TASK_ID}
        h1 = planning_handoff(state)
        state["messages"] = add_messages(state["messages"], h1["messages"])
        epoch = len(state["messages"])  # replan seam lands at this length
        state["attribution_epoch_index"] = epoch

        # Compaction removes pre-boundary messages (say the round-1 kickoff
        # and receipt — summaries replace them) and re-bases.
        pre_boundary = state["messages"][:epoch]
        to_compact = [m for m in pre_boundary if isinstance(m, ToolMessage)]
        removed_ids = {m.id for m in to_compact}
        state["messages"] = [
            m for m in state["messages"] if m.id not in removed_ids
        ]
        rebased = _rebase_epoch_index(state["messages"], to_compact, epoch)
        assert rebased is not None and rebased < epoch
        state["attribution_epoch_index"] = rebased

        # The epoch slice stays semantically valid: everything from the
        # rebased boundary onward is the post-seam history, intact.
        slice_ids = {m.id for m in state["messages"][rebased:]}
        assert not slice_ids & removed_ids

    def test_compaction_then_handoff(self, monkeypatch):
        # Compaction first: it removes pre-boundary messages and re-bases
        # the epoch index; the handoff's positional rules then locate the
        # finalized marker on the COMPACTED list and strip the new round.
        _patch_store(monkeypatch, _FakeStore())

        # Two-round sequence without any prior handoff strip.
        seq = list(add_messages([], [
            _anchor_fault_intent(),        # 0
            _anchor_probe_hints(),         # 1
            _ai_probe_turn("c1", "nodes"),  # 2
            _tool_result("c1", "..."),     # 3
            _finalized("round 1"),         # 4
            _kickoff(),                    # 5
            _exec_receipt(),               # 6
            _verify_turn(),                # 7
            _ai_probe_turn("c3", "..."),   # 8  (round 2 planning)
            _tool_result("c3", "..."),     # 9
            _finalized("round 2"),         # 10
        ]))
        state = {"messages": list(seq), "task_id": TASK_ID}
        state["attribution_epoch_index"] = 8

        # Compaction removes the pre-boundary planning turns (2, 3) and
        # re-bases the epoch from 8 to 6. The re-base counts survivors in
        # the PRE-deletion list — pass the original sequence.
        to_compact = [seq[2], seq[3]]
        removals = {m.id for m in to_compact}
        state["messages"] = [
            m for m in state["messages"] if m.id not in removals
        ]
        from chaos_agent.memory.hook import _rebase_epoch_index
        rebased = _rebase_epoch_index(seq, to_compact, 8)
        assert rebased == 6
        state["attribution_epoch_index"] = rebased

        # Handoff on the compacted list: range [6, finalized=8) still
        # selects exactly the round-2 planning turns.
        result = planning_handoff(state)
        assert {r.id for r in result["messages"]} == {seq[8].id, seq[9].id}


# ---------------------------------------------------------------------------
# Anchor generation sites (spec: anchors are marked at GENERATION time).
# ---------------------------------------------------------------------------


class TestAnchorGenerationSites:
    def test_probe_hints_message_carries_anchor_flag(self):
        from chaos_agent.agent.nodes.gates.preplan_probe import _observation_message

        msg = _observation_message({
            "chaosblade_operator": {
                "status": "ok", "summary": "running", "detail": {},
            },
        })
        assert (msg.additional_kwargs or {}).get(CONTEXT_ANCHOR_FLAG) is True

    @pytest.mark.asyncio
    async def test_fault_intent_message_carries_anchor_flag(self, monkeypatch):
        # First planning round: agent_loop injects the FAULT INTENT
        # HumanMessage from the fault_spec state key — it must land with
        # the retention flag so the strip keeps it.
        import chaos_agent.agent.nodes.execute.agent_loop as loop_mod
        from chaos_agent.agent.nodes.execute.agent_loop import make_agent_loop
        from chaos_agent.agent.spec.fault_spec import FaultSpec

        llm = MagicMock()
        # The unbound LLM is used when the iteration leaves no visible
        # tools (``tools_this_iter`` empty → ``llm_with_tools = llm``);
        # bind_tools is the bound path. Both must be awaitable.
        llm.ainvoke = AsyncMock(return_value=AIMessage(content="planning..."))
        bound = MagicMock()
        bound.ainvoke = AsyncMock(return_value=AIMessage(content="planning..."))
        llm.bind_tools = MagicMock(return_value=bound)
        node = make_agent_loop(llm=llm, tools=[])
        monkeypatch.setattr(loop_mod, "compute_env_info", AsyncMock(return_value=""))
        monkeypatch.setattr(loop_mod, "sync_to_store", AsyncMock())

        spec = FaultSpec.from_cli_structured({
            "scope": "pod",
            "target": "kill",
            "action": "delete",
            "namespace": "default",
            "target_name": "my-pod",
            "params": {"duration": "60"},
        })
        result = await node({
            "task_id": "task-anchor-site",
            "operation": "inject",
            "agent_loop_count": 0,
            "messages": [],
            "fault_spec": spec.to_dict(),
        })

        fi_msgs = [
            m for m in result.get("messages", [])
            if isinstance(m, HumanMessage)
            and str(m.content).startswith("[FAULT INTENT")
        ]
        assert len(fi_msgs) == 1
        assert (fi_msgs[0].additional_kwargs or {}).get(CONTEXT_ANCHOR_FLAG) is True


# ---------------------------------------------------------------------------
# Replica-fallback survival (T0-1.4 pinning).
# ---------------------------------------------------------------------------


class TestReplicaFallbackSurvival:
    def test_phase2_get_then_scale_extraction_survives_strip(self, monkeypatch):
        # The scale fallback scans ToolMessages for pre-scale ``kubectl
        # get`` JSON. A get issued in the EXECUTION segment sits in the
        # retained zone (after the finalized marker), so the extraction
        # still works after the planning strip.
        from chaos_agent.agent.nodes.execute.execute_loop import (
            _extract_original_replicas_from_messages,
        )

        _patch_store(monkeypatch, _FakeStore())
        get_json = (
            '{"kind": "Deployment", "metadata": {"name": "web"}, '
            '"spec": {"replicas": 3}}'
        )
        seq = list(add_messages([], [
            _anchor_fault_intent(),
            _anchor_probe_hints(),
            _ai_probe_turn("c1", "get deployments"),
            _tool_result("c1", "old probe output"),  # planning get — stripped
            _finalized(),
            _kickoff(),
            _ai_probe_turn("c9", "get deployment web -o json"),
            _tool_result("c9", get_json),  # execution get — retained
        ]))
        state = {"messages": list(seq), "task_id": TASK_ID}

        result = planning_handoff(state)
        state["messages"] = add_messages(state["messages"], result["messages"])

        assert _extract_original_replicas_from_messages(
            state["messages"], "web"
        ) == 3
